grails-app/controllers/twitter/RegisterController.groovy
package twitter

import grails.plugin.springsecurity.annotation.Secured
import twitter.auth.Role
import twitter.auth.User
import twitter.auth.UserRole

@Secured('permitAll')
class RegisterController {

    def mailService

    def index() {}

    def registration() {
        if (params.password != params.password2) {        // Passwords don't match
            render view: "index", model: [serverMessage: "Passwords don't match"]
            return
        }

        def user = User.findByUsername(params.username)     // User exists
        if (user) {
            render view: "index", model: [serverMessage: "There is already an user with this username"]
            return
        }

        // Create a new user object
        def userInstance = new User(username: params.username, password: params.password, realName: params.realName, email: params.email)
        userInstance.save(flush: true, failOnError: true)

        // Assign role to user
        def roleUser = Role.findByAuthority('ROLE_USER')
        UserRole.create userInstance, roleUser, true

        //Send a confirmation email to the new user
        userInstance.enabled = true
        userInstance.accountLocked = false
        userInstance.accountExpired = false
        userInstance.passwordExpired = false

        // Create a new random confirmation code for the user
        userInstance.confirmCode = UUID.randomUUID().toString()

        if (!userInstance.save(flush: true)) {
            return
        }

        mailService.sendMail {
            to userInstance.email
            subject "New User Confirmation"
            html g.render(template: "../templates/mail", model: [code: userInstance.confirmCode])
        }

        render view: "index", model: [serverMessage: "Your account has been creeated. Please confirm your email address. Confirmation link has been sent to your account."]
        redirect(action: "success")

    }

    def success() {
        render(view: 'success', model: [message: 'Your account has been creeated. Please confirm your email address. Confirmation link has been sent to your account']);
    }

    def confirm(String ConfirmCode) {
        User userInstance = User.findByConfirmCode(ConfirmCode)
        if (!userInstance) {
            return;
        }
        // Change the user's confirmation code since it must be used only once
        userInstance.confirmCode = ''

        if (!userInstance.save(flush: true)) {
            render(view: "success", model: [message: 'Problem activating account.'])
            return
        }
        render(view: "success", model: [message: 'You account is successfully activated. Now you can login'])
    }
}

grails-app/views/register/index.gsp
<html>
<head>
    <meta name='layout' content='main'/>
    <title>Register</title>
    <style type='text/css' media='screen'>
    #login {
        margin: 15px 0px;
        padding: 0px;
        text-align: center;
    }

    #login .inner {
        width: 340px;
        padding-top: 30px;
        margin: 60px auto;
        text-align: left;
        border: 1px solid #aab;
        background-color: #f0f0fa;
        -moz-box-shadow: 2px 2px 2px #eee;
        -webkit-box-shadow: 2px 2px 2px #eee;
        -khtml-box-shadow: 2px 2px 2px #eee;
        box-shadow: 2px 2px 2px #eee;
    }

    #login .inner .fheader {
        padding: 18px 26px 14px 26px;
        background-color: #f7f7ff;
        margin: 0px 0 14px 0;
        color: #2e3741;
        font-size: 18px;
        font-weight: bold;
    }

    #login .inner .cssform p {
        clear: left;
        margin: 0;
        padding: 4px 0 3px 0;
        padding-left: 105px;
        margin-bottom: 20px;
        height: 1%;
    }

    #login .inner .cssform input[type='text'] {
        width: 220px;
    }

    #login .inner .cssform label {
        font-weight: bold;
        float: left;
        text-align: right;
        margin-left: -105px;
        width: 110px;
        padding-top: 3px;
        padding-right: 10px;
    }

    #login #remember_me_holder {
        padding-left: 120px;
    }

    #login #submit {
        margin-left: 15px;
    }

    #login #remember_me_holder label {
        float: none;
        margin-left: 0;
        text-align: left;
        width: 200px
    }

    #login .inner .login_message {
        padding: 6px 25px 20px 25px;
        color: #c33;
    }

    #login .inner .text_ {
        width: 220px;
    }

    #login .inner .chk {
        height: 12px;
    }
    body {
        background: #00b4ff;
        color: #333;
        height: 100vh;
        margin: 0;
        padding: 0;
        overflow-x: hidden;
    }

    #background-wrap {
        bottom: 0;
        left: 0;
        padding-top: 50px;
        position: fixed;
        right: 0;
        top: 0;
        z-index: -1;
    }

    /* KEYFRAMES */

    @-webkit-keyframes animateCloud {
        0% {
            margin-left: -1000px;
        }
        100% {
            margin-left: 100%;
        }
    }

    @-moz-keyframes animateCloud {
        0% {
            margin-left: -1000px;
        }
        100% {
            margin-left: 100%;
        }
    }

    @keyframes animateCloud {
        0% {
            margin-left: -1000px;
        }
        100% {
            margin-left: 100%;
        }
    }

    /* ANIMATIONS */

    .x1 {
        -webkit-animation: animateCloud 35s linear infinite;
        -moz-animation: animateCloud 35s linear infinite;
        animation: animateCloud 35s linear infinite;

        -webkit-transform: scale(0.65);
        -moz-transform: scale(0.65);
        transform: scale(0.65);
    }

    .x2 {
        -webkit-animation: animateCloud 20s linear infinite;
        -moz-animation: animateCloud 20s linear infinite;
        animation: animateCloud 20s linear infinite;

        -webkit-transform: scale(0.3);
        -moz-transform: scale(0.3);
        transform: scale(0.3);
    }

    .x3 {
        -webkit-animation: animateCloud 30s linear infinite;
        -moz-animation: animateCloud 30s linear infinite;
        animation: animateCloud 30s linear infinite;

        -webkit-transform: scale(0.5);
        -moz-transform: scale(0.5);
        transform: scale(0.5);
    }

    .x4 {
        -webkit-animation: animateCloud 18s linear infinite;
        -moz-animation: animateCloud 18s linear infinite;
        animation: animateCloud 18s linear infinite;

        -webkit-transform: scale(0.4);
        -moz-transform: scale(0.4);
        transform: scale(0.4);
    }

    .x5 {
        -webkit-animation: animateCloud 25s linear infinite;
        -moz-animation: animateCloud 25s linear infinite;
        animation: animateCloud 25s linear infinite;

        -webkit-transform: scale(0.55);
        -moz-transform: scale(0.55);
        transform: scale(0.55);
    }

    /* OBJECTS */

    .cloud {
        background: #fff;
        background: -moz-linear-gradient(top,  #fff 5%, #f1f1f1 100%);
        background: -webkit-gradient(linear, left top, left bottom, color-stop(5%,#fff), color-stop(100%,#f1f1f1));
        background: -webkit-linear-gradient(top,  #fff 5%,#f1f1f1 100%);
        background: -o-linear-gradient(top,  #fff 5%,#f1f1f1 100%);
        background: -ms-linear-gradient(top,  #fff 5%,#f1f1f1 100%);
        background: linear-gradient(top,  #fff 5%,#f1f1f1 100%);
        filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#fff', endColorstr='#f1f1f1',GradientType=0 );

        -webkit-border-radius: 100px;
        -moz-border-radius: 100px;
        border-radius: 100px;

        -webkit-box-shadow: 0 8px 5px rgba(0, 0, 0, 0.1);
        -moz-box-shadow: 0 8px 5px rgba(0, 0, 0, 0.1);
        box-shadow: 0 8px 5px rgba(0, 0, 0, 0.1);

        height: 120px;
        position: relative;
        width: 350px;
    }

    .cloud:after, .cloud:before {
        background: #fff;
        content: '';
        position: absolute;
        z-indeX: -1;
    }

    .cloud:after {
        -webkit-border-radius: 100px;
        -moz-border-radius: 100px;
        border-radius: 100px;

        height: 100px;
        left: 50px;
        top: -50px;
        width: 100px;
    }

    .cloud:before {
        -webkit-border-radius: 200px;
        -moz-border-radius: 200px;
        border-radius: 200px;

        width: 180px;
        height: 180px;
        right: 50px;
        top: -90px;
    }
    </style>
</head>

<body>
<div id="background-wrap">
    <div class="x1">
        <div class="cloud"></div>
    </div>

    <div class="x2">
        <div class="cloud"></div>
    </div>

    <div class="x3">
        <div class="cloud"></div>
    </div>

    <div class="x4">
        <div class="cloud"></div>
    </div>

    <div class="x5">
        <div class="cloud"></div>
    </div>
</div>
<div id='login'>
    <div class='inner'>

        <g:form action='registration' method="POST" controller="register" class='cssform' autocomplete='off'>

            <div class="fheader"> Register </div>
            <p>
                <label for='username'><g:message code="springSecurity.login.username.label"/>:</label>
                <input type='text' class='text_' name='username' id='username' required/>
            </p>
            <p>
                <label for='realName'><g:message code="Your real name"/>:</label>
                <input type='text' class='text_' name='realName' id='realName' required/>
            </p>
            <p>
                <label for='email'><g:message code="Your email"/>:</label>
                <input type='email' class='text_' name='email' id='email' required/>
            </p>
            <p>
                <label for='password'><g:message code="Password"/>:</label>
                <input type='password' class='text_' name='password' id='password' required/>
            </p>
            <p>
                <label for='password2'><g:message code="Repeat Password"/></label>
                <input type='password' class='text_' name='password2' id='password2' required/>
            </p>

            <p id="formMEssage">
                ${serverMessage}
            </p>
            <p>
                <input type='submit' class="button" id="submit" value='Register'/>
            </p>
        </g:form>
    </div>
</div>

</body>
</html>

grails-app/views/register/registration.gsp
<html>
<head>
    <meta name='layout' content='main'/>
    <title>Register</title>
    <style type='text/css' media='screen'>
    #login {
        margin: 15px 0px;
        padding: 0px;
        text-align: center;
    }

    #login .inner {
        width: 340px;
        padding-bottom: 6px;
        margin: 60px auto;
        text-align: left;
        border: 1px solid #aab;
        background-color: #f0f0fa;
        -moz-box-shadow: 2px 2px 2px #eee;
        -webkit-box-shadow: 2px 2px 2px #eee;
        -khtml-box-shadow: 2px 2px 2px #eee;
        box-shadow: 2px 2px 2px #eee;
    }

    #login .inner .fheader {
        padding: 18px 26px 14px 26px;
        background-color: #f7f7ff;
        margin: 0px 0 14px 0;
        color: #2e3741;
        font-size: 18px;
        font-weight: bold;
    }

    #login .inner .cssform p {
        clear: left;
        margin: 0;
        padding: 4px 0 3px 0;
        padding-left: 105px;
        margin-bottom: 20px;
        height: 1%;
    }

    #login .inner .cssform input[type='text'] {
        width: 120px;
    }

    #login .inner .cssform label {
        font-weight: bold;
        float: left;
        text-align: right;
        margin-left: -105px;
        width: 110px;
        padding-top: 3px;
        padding-right: 10px;
    }

    #login #remember_me_holder {
        padding-left: 120px;
    }

    #login #submit {
        margin-left: 15px;
    }

    #login #remember_me_holder label {
        float: none;
        margin-left: 0;
        text-align: left;
        width: 200px
    }

    #login .inner .login_message {
        padding: 6px 25px 20px 25px;
        color: #c33;
    }

    #login .inner .text_ {
        width: 120px;
    }

    #login .inner .chk {
        height: 12px;
    }
    </style>
</head>

<body>
<div id='login'>
    <div class='inner'>

        <g:form action='registration' method="POST" controller="register" class='cssform' autocomplete='off'>
            <p>
                <label for='username'><g:message code="springSecurity.login.username.label"/>:</label>
                <input type='text' class='text_' name='username' id='username' />
            </p>
            <p>
                <label for='realName'><g:message code="Your real name"/>:</label>
                <input type='text' class='text_' name='realName' id='realName' />
            </p>
            <p>
                <label for='email'><g:message code="Your email"/>:</label>
                <input type='email' class='text_' name='email' id='email' />
            </p>
            <p>
                <label for='password'><g:message code="Password"/>:</label>
                <input type='password' class='text_' name='password' id='password' />
            </p>
            <p>
                <label for='password2'><g:message code="Repeat Password"/></label>
                <input type='password' class='text_' name='password2' id='password2' />
            </p>

            <p id="formMEssage">
                ${serverMessage}
            </p>
            <p>
                <input type='submit' id="submit" value='Register'/>
            </p>
        </g:form>
    </div>
</div>

</body>
</html>

grails-app/views/register/success.gsp
<div class="container">
    <h1>Registration</h1>
    <div class="alert alert-success">
        ${message}
    </div>
    <g:link controller="login" action="auth">
        Login
    </g:link>
</div>